import studentRouter from "./studentPaths.js";
import programRouter from "./programPaths.js";
import courseRouter from "./coursePaths.js";
import bodyParser from "body-parser";
import express from "express";
const mainRouter = express.Router();
// mainRouter.use(bodyParser.json());
mainRouter.use(express.json());
mainRouter.use("/api", studentRouter);
mainRouter.use("/api",programRouter);
mainRouter.use("/api",courseRouter);
export default mainRouter;